version: '3'
services:
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.59.1
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943" 
  shop:
    image: shabushabu/javashop.shop:latest
    ports:
      - "8010:8010"
    links:
      - splunk-otel-collector
      - products
      - stock
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      - splunk-otel-collector
  products:
    image:  shabushabu/javashop.products:latest
    ports:
      - "8020:8020"
    links:
      - splunk-otel-collector
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:    
      - splunk-otel-collector
  stock:
    image: shabushabu/javashop.stock:latest
    ports:
      - "8030:8030"
    links:
      - splunk-otel-collector
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      - splunk-otel-collector
  shoptester:
    image: shabushabu/javashop.tester:latest
    links:
      - shop
      - splunk-otel-collector
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      - shop
