version: '3'
services:
  shop:
          #network_mode: host
    image: shabushabu/javashop.shop:latest
    #command: -server -advertise HOSTIP -bootstrap
    ports:
      - "8010:8010"
    links:
      - products
      - stock
    environment:
     - USERNAME=${USERNAME}
     - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
  products:
          #network_mode: host
    image:  shabushabu/javashop.products:latest
    #command: -server -advertise HOSTIP -bootstrap
    ports:
      - "8020:8020"
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
  stock:
          #network_mode: host
    image: shabushabu/javashop.stock:latest
    #command: -server -advertise HOSTIP -bootstrap
    ports:
      - "8030:8030"
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
  shoptester:
          #network_mode: host
    image: shabushabu/javashop.tester:latest
    #command: -server -advertise HOSTIP -bootstrap
    links:
      - shop
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}

