version: '3'
services:
  shop:
    image: shabushabu/javashop.shop:latest
    ports:
      - "8010:8010"
    links:
      - products
      - stock
    environment:
     - USERNAME=${USERNAME}
  products:
    image:  shabushabu/javashop.products:latest
    ports:
      - "8020:8020"
    environment:
      - USERNAME=${USERNAME}
  stock:
    image: shabushabu/javashop.stock:latest
    ports:
      - "8030:8030"
    environment:
      - USERNAME=${USERNAME}
