version: '3'
services:
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.59.1
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943" 
  shop:
    image: shabushabu/javashop.shop:latest
    build:
      ./shop
    ports:
      - "8010:8010"
    links:
      - splunk-otel-collector
      - products
      - stock
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      - splunk-otel-collector
      - products
      - stock
      - instruments
  products:
    image:  shabushabu/javashop.products:latest
    build:
      ./products
    ports:
      - "8020:8020"
    links:
      - splunk-otel-collector
      - postgres
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:    
      - splunk-otel-collector
  stock:
    image: shabushabu/javashop.stock:latest
    build:
      ./stock
    ports:
      - "8030:8030"
    links:
      - splunk-otel-collector
      - postgres
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      - splunk-otel-collector
      - postgres
  shoptester:
    image: shabushabu/javashop.tester:latest
    build:
      ./test
    links:
      - shop
      - splunk-otel-collector
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      - shop
      - splunk-otel-collector
  instruments:
    image:  shabushabu/javashop.instruments:latest
    build:
      ./instruments
    ports:
      - "8040:8040"
    links:
      - splunk-otel-collector
      - postgres
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - splunk-otel-collector  
      - postgres
  postgres:
    image: "postgres:13.1-alpine"
    restart: always
    environment:
      - POSTGRES_USER=compose_postgres
      - POSTGRES_PASSWORD=compose_postgres
    ports:
      - "5438:5432"
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - .db/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql


