version: '3'
services:
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.59.1
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943" 
    healthcheck:
      #test: curl --fail http://localhost:13133 || exit 1
      test: curl -sS http://localhost:13133 | grep -c "status":"Server available" > /dev/null
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 3s
  shop:
    image: shabushabu/javashop.shop:latest
    build:
      ./shop
    ports:
      - "8010:8010"
    links:
      - splunk-otel-collector
      - products
      - stock
      - instruments
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    healthcheck:
      test: curl -sS http://localhost:8010/healthcheck | grep -c 200 > /dev/null
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      splunk-otel-collector:
        condition: service_started
      products:
        condition: service_healthy
      stock:
        condition: service_healthy
      instruments:
        condition: service_healthy
  products:
    image: shabushabu/javashop.products:latest
    build:
      ./products
    ports:
      - "8020:8020"
    healthcheck:
      test: curl -sS http://localhost:8020/products/healthcheck | grep -c 200 > /dev/null
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s
    links:
      - splunk-otel-collector
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      splunk-otel-collector:
        condition: service_started
  stock:
    image: shabushabu/javashop.stock:latest
    build:
      ./stock
    ports:
      - "8030:8030"
    healthcheck:
      test: curl -sS http://localhost:8030/healthcheck | grep -c 200 > /dev/null
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s
    links:
      - splunk-otel-collector
      - instruments
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/compose-postgres
      #- SPRING_DATASOURCE_USERNAME=compose-postgres
      #- SPRING_DATASOURCE_PASSWORD=compose-postgres
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
     # - splunk-otel-collector
      splunk-otel-collector:
         condition: service_started
      #  condition: service_healthy
      instruments:
        condition: service_healthy
  shoptester:
    image: shabushabu/javashop.tester:latest
    build:
      ./test
    links:
      - shop
      - splunk-otel-collector
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    depends_on:
      splunk-otel-collector:
        condition: service_started
      shop: 
        condition: service_healthy
      products:
        condition: service_healthy
      stock:
        condition: service_healthy
      instruments:
        condition: service_healthy
  instruments:
    image:  shabushabu/javashop.instruments:latest
    build:
      ./instruments
    ports:
      - "8040:8040"
    healthcheck:
      test: curl -sS http://localhost:8040/healthcheck | grep -c 200 > /dev/null
      #curl --fail http://localhost:8040//healthcheck  || exit 1
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s
    links:
      - splunk-otel-collector
      - postgresDB
    environment:
      - USERNAME=${USERNAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/instruments
      - SPRING_DATASOURCE_USERNAME=instruments
      - SPRING_DATASOURCE_PASSWORD=instruments
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      splunk-otel-collector:
        condition: service_started
      postgresDB:
        condition: service_healthy
  postgresDB:
    image: "postgres:13.1-alpine"
    container_name: postgresDB
    environment:
      - POSTGRES_USER=instruments
      - POSTGRES_PASSWORD=instruments
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./db/sql/instruments-latest.sql:/docker-entrypoint-initdb.d/instruments-latest.sql
      - ./db/sql/instruments-chicago.sql:/docker-entrypoint-initdb.d/instruments-chicago.sql


