version: '3.7'

services:
  postgres:
    image: "postgres:13.1-alpine"
    restart: always
    environment: 
      - POSTGRES_USER=compose_postgres
      - POSTGRES_PASSWORD=compose_postgres
    ports:
      - "5438:5432"
    volumes:
      - ./sql/instruments.sql:/docker-entrypoint-initdb.d/instruments.sql 
      - ./sql/stocks.sql:/docker-entrypoint-initdb.d/stocks.sql
